version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: mirkat-frontend
    container_name: frontend
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../api
      dockerfile: Dockerfile
    image: mirkat-backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ../api/images:/app/images
      - ../api/images-news:/app/images-news