version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"